In [18]:
import pandas as pd

Código inicial para limpar dados do applicants.json

In [19]:
# df_applicants = pd.read_json('data/applicants.json', orient='index')

# df_applicants.head()

In [20]:
# infos_basicas = pd.json_normalize(df_applicants['infos_basicas'])
# informacoes_pessoais = pd.json_normalize(df_applicants['informacoes_pessoais'])
# informacoes_profissionais = pd.json_normalize(df_applicants['informacoes_profissionais'])
# formacao_e_idiomas = pd.json_normalize(df_applicants['formacao_e_idiomas'])
# cargo_atual = pd.json_normalize(df_applicants['cargo_atual'])

# df_applicants = pd.concat([infos_basicas, informacoes_pessoais, informacoes_profissionais, formacao_e_idiomas, cargo_atual], axis=1)

# column_numbers = [x for x in range(df_applicants.shape[1])]
# column_numbers.remove(10)
# df_applicants = df_applicants.iloc[:, column_numbers]

Reimport via CSV para conseguir subir no GitHub.

In [21]:
df_applicants = pd.read_csv('data/applicants.csv', index_col=0)

/tmp/ipykernel_4715/3426563353.py:1: DtypeWarning: Columns (35,36,48,53,54) have mixed types. Specify dtype option on import or set low_memory=False.
  df_applicants = pd.read_csv('data/applicants.csv', index_col=0)

In [22]:
df_prospects = pd.read_json('data/prospects.json', orient='index')

df_prospects

,titulo,modalidade,prospects
4530,CONSULTOR CONTROL M,,"[{'nome': 'José Vieira', 'codigo': '25632', 's..."
4531,2021-2607395-PeopleSoft Application Engine-Dom...,,"[{'nome': 'Sra. Yasmin Fernandes', 'codigo': '..."
4532,,,[]
4533,2021-2605708-Microfocus Application Life Cycle...,,"[{'nome': 'Arthur Almeida', 'codigo': '26338',..."
4534,2021-2605711-Microfocus QTP - UFT Automation T...,,"[{'nome': 'Ana Luiza Vieira', 'codigo': '26361..."
...,...,...,...
14218,Java Support Analyst,,"[{'nome': 'Dr. Vitor Hugo Silva', 'codigo': '4..."
14219,,,[]
14220,Consultor Sênior Especialista SAP LES-TRA - 1433,,"[{'nome': 'Ana Cardoso', 'codigo': '16828', 's..."
14221,Consultor Sênior Oracle EPM FCCS - 1434,,"[{'nome': 'Maria Eduarda Cassiano', 'codigo': ..."
14222,,,[]

In [23]:
# Read the JSON file
df_prospects = pd.read_json('data/prospects.json', orient='index')

# Ensure 'prospects' column exists for all rows
df_prospects['prospects'] = df_prospects.get('prospects', pd.Series([[]]*len(df_prospects), index=df_prospects.index))

# Explode the 'prospects' list so each prospect gets its own row
df_exploded = df_prospects.explode('prospects')

# Drop rows where 'prospects' is still empty (i.e., NaN after explode)
df_exploded = df_exploded.dropna(subset=['prospects'])

# Normalize the 'prospects' dictionaries into columns
if not df_exploded.empty:
    df_normalized = pd.json_normalize(df_exploded['prospects'])
    # Combine with the index (IDs)
    df_result = df_exploded.drop(columns=['prospects']).join(df_normalized)
else:
    df_result = pd.DataFrame()  # No prospects to normalize

df_result.head()

,titulo,modalidade,nome,codigo,situacao_candidado,data_candidatura,ultima_atualizacao,comentario,recrutador
4530,CONSULTOR CONTROL M,,Kaique Almeida,34491,Entrevista Técnica,30-03-2022,13-04-2022,Avaliação pela em 13/04,Elisa Barbosa
4530,CONSULTOR CONTROL M,,Kaique Almeida,34491,Entrevista Técnica,30-03-2022,13-04-2022,Avaliação pela em 13/04,Elisa Barbosa
4531,2021-2607395-PeopleSoft Application Engine-Dom...,,Dr. Luiz Otávio Viana,34162,Prospect,17-03-2022,17-03-2022,,Yasmin da Rosa
4531,2021-2607395-PeopleSoft Application Engine-Dom...,,Dr. Luiz Otávio Viana,34162,Prospect,17-03-2022,17-03-2022,,Yasmin da Rosa
4533,2021-2605708-Microfocus Application Life Cycle...,,Ryan Cassiano,13960,Prospect,04-04-2022,04-04-2022,,Srta. Bella Ferreira

In [24]:
df_prospects = df_result

In [25]:
df_prospects

,titulo,modalidade,nome,codigo,situacao_candidado,data_candidatura,ultima_atualizacao,comentario,recrutador
4530,CONSULTOR CONTROL M,,Kaique Almeida,34491,Entrevista Técnica,30-03-2022,13-04-2022,Avaliação pela em 13/04,Elisa Barbosa
4530,CONSULTOR CONTROL M,,Kaique Almeida,34491,Entrevista Técnica,30-03-2022,13-04-2022,Avaliação pela em 13/04,Elisa Barbosa
4531,2021-2607395-PeopleSoft Application Engine-Dom...,,Dr. Luiz Otávio Viana,34162,Prospect,17-03-2022,17-03-2022,,Yasmin da Rosa
4531,2021-2607395-PeopleSoft Application Engine-Dom...,,Dr. Luiz Otávio Viana,34162,Prospect,17-03-2022,17-03-2022,,Yasmin da Rosa
4533,2021-2605708-Microfocus Application Life Cycle...,,Ryan Cassiano,13960,Prospect,04-04-2022,04-04-2022,,Srta. Bella Ferreira
...,...,...,...,...,...,...,...,...,...
14217,SAP SD,,Amanda Gonçalves,14289,Não Aprovado pelo Requisitante,22-02-2019,26-02-2019,A experiência da Ana é muito pequena ( nível j...,Helena Barros
14218,Java Support Analyst,,Ana Vitória Albuquerque,14245,Inscrito,20-02-2019,,,Caroline Machado
14220,Consultor Sênior Especialista SAP LES-TRA - 1433,,Miguel Pereira,14213,Encaminhado ao Requisitante,19-02-2019,19-02-2019,"Modalidade: Cooperado Valor de compra: R$ 60,0...",Srta. Bella Ferreira
14220,Consultor Sênior Especialista SAP LES-TRA - 1433,,Miguel Pereira,14213,Encaminhado ao Requisitante,19-02-2019,19-02-2019,"Modalidade: Cooperado Valor de compra: R$ 60,0...",Srta. Bella Ferreira
14221,Consultor Sênior Oracle EPM FCCS - 1434,,Luan Marques,3217,Encaminhado ao Requisitante,19-02-2019,19-02-2019,"Modalidade: Cooperado Valor de compra: R$ 50,0...",Srta. Bella Ferreira

#### Temos df_applicants, df_prospects agora.

In [26]:
# Read the JSON file as a dictionary of dictionaries
df_vagas = pd.read_json('data/vagas.json', orient='index')

# Normalize each dictionary column
infos_basicas = pd.json_normalize(df_vagas['informacoes_basicas'])
perfil_vaga = pd.json_normalize(df_vagas['perfil_vaga'])
beneficios = pd.json_normalize(df_vagas['beneficios'])

# Concatenate all normalized columns with the original index
df_vagas = pd.concat([infos_basicas, perfil_vaga, beneficios], axis=1)

# Show the flattened DataFrame
df_vagas

,data_requicisao,limite_esperado_para_contratacao,titulo_vaga,vaga_sap,cliente,solicitante_cliente,empresa_divisao,requisitante,analista_responsavel,tipo_contratacao,...,areas_atuacao,principais_atividades,competencia_tecnicas_e_comportamentais,demais_observacoes,viagens_requeridas,equipamentos_necessarios,habilidades_comportamentais_necessarias,valor_venda,valor_compra_1,valor_compra_2
0,04-05-2021,00-00-0000,Operation Lead -,Não,"Morris, Moran and Dodson",Dra. Catarina Marques,Decision São Paulo,Maria Laura Nogueira,Srta. Bella Ferreira,CLT Full,...,TI - Sistemas e Ferramentas-,Operations Lead\n\nRoles & Responsibilities:\n...,Required Skills:\n• Prior experience in Cloud ...,100% Remoto Período – entre 5 – 6 meses,,Nenhum -,NaN,-,R$,
1,04-05-2021,00-00-0000,Consultor PP/QM Sênior,Não,"Morris, Moran and Dodson",Dra. Catarina Marques,Decision São Paulo,Maria Laura Nogueira,Yasmin da Rosa,CLT Full,...,TI - Desenvolvimento/Programação-,Consultor PP/QM Sr.\n\n• Consultor PP/QM Sênio...,• Consultor PP/QM Sênior com experiencia em pr...,• Início: Imediato • Fim: Jan/22,,Nenhum -,NaN,-,R$,
2,04-05-2021,00-00-0000,ANALISTA PL/JR C/ SQL,Não,"Morris, Moran and Dodson",Dra. Catarina Marques,Decision São Paulo,Maria Laura Nogueira,Ana Albuquerque,CLT Full,...,TI - Sistemas e Ferramentas-,Descrição – Atividades:\n\no Monitoramento das...,Requisitos mandatórios:\n\no Conhecimentos Téc...,Localização: Remoto Perfil: Analista Pleno ou ...,,Nenhum -,NaN,-,R$,
3,04-05-2021,18-05-2021,Technical Architect - 11894809,Não,Nelson-Page,Dr. Raul Monteiro,Decision São Paulo,Cecília Freitas,Clara Rios,"PJ/Autônomo, CLT Full",...,TI - Projetos-,Descrição/Comentário: Architecture Frameworks ...,Descrição/Comentário: Architecture Frameworks ...,Budgeted Rate - indicate currency and type (ho...,Não,Notebook padrão -,NaN,- p/ mês (168h),fechado,
4,04-05-2021,00-00-0000,Consultor SAP AUTHORIZATION (BCA) -Pleno / Sênior,Não,Mann and Sons,Cauê Fogaça,Decision São Paulo,Maria Laura Nogueira,Srta. Bella Ferreira,CLT Full,...,TI - SAP-,Experiência como Consultor SAP AUTHORIZATION (...,Experiência como Consultor SAP AUTHORIZATION (...,contratação CLT full pela Decision locação rem...,Sim,Nenhum -,NaN,-,R$,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14076,28-02-2024,31-03-2024,PMP 5203658 - Dynamics,Não,Miller-Curry,Guilherme Campos,Decision Campinas,Sra. Juliana Oliveira,Sra. Joana Sousa,CLT Full,...,TI - Desenvolvimento/Programação-,Dynamics,Dynamics,,,,NaN,"123,00 -",APPLICATION DEVELOPER-MICROSOFT ANALYTICS - ba...,
14077,28-02-2024,29-02-2024,MM com IM - FSR 3910,Não,Bishop-Reed,Lívia Vasconcelos,Decision São Paulo,Manuella Jesus,Srta. Bella Ferreira,"CLT Full, PJ/Autônomo",...,TI - Projetos-,1 Deve ter boa experiência em configuração de ...,inglês avançado: (tem que se comunicar com o G...,FSR: 3910,Não,,NaN,168 -,Fechado,
14078,27-02-2024,29-02-2024,964 - Assistente fiscal ou financeiro,Não,"Glover, Warren and Norris",Lorenzo Cunha,Decision São Paulo,Maria Lopes,Maria Clara Pires,"CLT Full, PJ/Autônomo",...,TI - Projetos-,Qualificações técnicas: conhecimento básico em...,"Local: Alphaville, Barueri\nQual região: SP\nI...","Modelo de trabalho: Hibrido, 3 vezes por seman...",Não,,NaN,168 -,Fechado,
14079,27-02-2024,29-02-2024,966 - Analista pleno ou sênior de área fiscal,Não,"Glover, Warren and Norris",Lorenzo Cunha,Decision São Paulo,Maria Lopes,Melina Montenegro,"CLT Full, PJ/Autônomo",...,TI - Projetos-,Qualificações técnicas: apuração de impostos r...,"Local: Alphaville, Barueri, SP.\nQual região: ...","Modelo de trabalho: Hibrido, 3 vezes por seman...",Não,,NaN,168 -,Fechado,
14080,27-02-2024,29-02-2024,965 - Assistente ou analista de área contábil,Não,"Glover, Warren and Norris",Lorenzo Cunha,Decision São Paulo,Maria Lopes,Laura Pacheco,"CLT Full, PJ/Autônomo",...,TI - Projetos-,Qualificações técnicas: reconciliação de conta...,"Local: Alphaville, Barueri, SP.\nRegião: Grand...","Modelo de trabalho: Hibrido, 3 vezes por seman...",Não,,NaN,168 -,Fechado,

In [27]:
df_vagas

,data_requicisao,limite_esperado_para_contratacao,titulo_vaga,vaga_sap,cliente,solicitante_cliente,empresa_divisao,requisitante,analista_responsavel,tipo_contratacao,...,areas_atuacao,principais_atividades,competencia_tecnicas_e_comportamentais,demais_observacoes,viagens_requeridas,equipamentos_necessarios,habilidades_comportamentais_necessarias,valor_venda,valor_compra_1,valor_compra_2
0,04-05-2021,00-00-0000,Operation Lead -,Não,"Morris, Moran and Dodson",Dra. Catarina Marques,Decision São Paulo,Maria Laura Nogueira,Srta. Bella Ferreira,CLT Full,...,TI - Sistemas e Ferramentas-,Operations Lead\n\nRoles & Responsibilities:\n...,Required Skills:\n• Prior experience in Cloud ...,100% Remoto Período – entre 5 – 6 meses,,Nenhum -,NaN,-,R$,
1,04-05-2021,00-00-0000,Consultor PP/QM Sênior,Não,"Morris, Moran and Dodson",Dra. Catarina Marques,Decision São Paulo,Maria Laura Nogueira,Yasmin da Rosa,CLT Full,...,TI - Desenvolvimento/Programação-,Consultor PP/QM Sr.\n\n• Consultor PP/QM Sênio...,• Consultor PP/QM Sênior com experiencia em pr...,• Início: Imediato • Fim: Jan/22,,Nenhum -,NaN,-,R$,
2,04-05-2021,00-00-0000,ANALISTA PL/JR C/ SQL,Não,"Morris, Moran and Dodson",Dra. Catarina Marques,Decision São Paulo,Maria Laura Nogueira,Ana Albuquerque,CLT Full,...,TI - Sistemas e Ferramentas-,Descrição – Atividades:\n\no Monitoramento das...,Requisitos mandatórios:\n\no Conhecimentos Téc...,Localização: Remoto Perfil: Analista Pleno ou ...,,Nenhum -,NaN,-,R$,
3,04-05-2021,18-05-2021,Technical Architect - 11894809,Não,Nelson-Page,Dr. Raul Monteiro,Decision São Paulo,Cecília Freitas,Clara Rios,"PJ/Autônomo, CLT Full",...,TI - Projetos-,Descrição/Comentário: Architecture Frameworks ...,Descrição/Comentário: Architecture Frameworks ...,Budgeted Rate - indicate currency and type (ho...,Não,Notebook padrão -,NaN,- p/ mês (168h),fechado,
4,04-05-2021,00-00-0000,Consultor SAP AUTHORIZATION (BCA) -Pleno / Sênior,Não,Mann and Sons,Cauê Fogaça,Decision São Paulo,Maria Laura Nogueira,Srta. Bella Ferreira,CLT Full,...,TI - SAP-,Experiência como Consultor SAP AUTHORIZATION (...,Experiência como Consultor SAP AUTHORIZATION (...,contratação CLT full pela Decision locação rem...,Sim,Nenhum -,NaN,-,R$,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14076,28-02-2024,31-03-2024,PMP 5203658 - Dynamics,Não,Miller-Curry,Guilherme Campos,Decision Campinas,Sra. Juliana Oliveira,Sra. Joana Sousa,CLT Full,...,TI - Desenvolvimento/Programação-,Dynamics,Dynamics,,,,NaN,"123,00 -",APPLICATION DEVELOPER-MICROSOFT ANALYTICS - ba...,
14077,28-02-2024,29-02-2024,MM com IM - FSR 3910,Não,Bishop-Reed,Lívia Vasconcelos,Decision São Paulo,Manuella Jesus,Srta. Bella Ferreira,"CLT Full, PJ/Autônomo",...,TI - Projetos-,1 Deve ter boa experiência em configuração de ...,inglês avançado: (tem que se comunicar com o G...,FSR: 3910,Não,,NaN,168 -,Fechado,
14078,27-02-2024,29-02-2024,964 - Assistente fiscal ou financeiro,Não,"Glover, Warren and Norris",Lorenzo Cunha,Decision São Paulo,Maria Lopes,Maria Clara Pires,"CLT Full, PJ/Autônomo",...,TI - Projetos-,Qualificações técnicas: conhecimento básico em...,"Local: Alphaville, Barueri\nQual região: SP\nI...","Modelo de trabalho: Hibrido, 3 vezes por seman...",Não,,NaN,168 -,Fechado,
14079,27-02-2024,29-02-2024,966 - Analista pleno ou sênior de área fiscal,Não,"Glover, Warren and Norris",Lorenzo Cunha,Decision São Paulo,Maria Lopes,Melina Montenegro,"CLT Full, PJ/Autônomo",...,TI - Projetos-,Qualificações técnicas: apuração de impostos r...,"Local: Alphaville, Barueri, SP.\nQual região: ...","Modelo de trabalho: Hibrido, 3 vezes por seman...",Não,,NaN,168 -,Fechado,
14080,27-02-2024,29-02-2024,965 - Assistente ou analista de área contábil,Não,"Glover, Warren and Norris",Lorenzo Cunha,Decision São Paulo,Maria Lopes,Laura Pacheco,"CLT Full, PJ/Autônomo",...,TI - Projetos-,Qualificações técnicas: reconciliação de conta...,"Local: Alphaville, Barueri, SP.\nRegião: Grand...","Modelo de trabalho: Hibrido, 3 vezes por seman...",Não,,NaN,168 -,Fechado,

#### Temos df_applicants, df_prospects e df_vagas agora.

##### Esta aplicação visa ranquear os 10 melhores candidatos para cada vaga.

In [28]:
df_vagas.columns

Index(['data_requicisao', 'limite_esperado_para_contratacao', 'titulo_vaga',
       'vaga_sap', 'cliente', 'solicitante_cliente', 'empresa_divisao',
       'requisitante', 'analista_responsavel', 'tipo_contratacao',
       'prazo_contratacao', 'objetivo_vaga', 'prioridade_vaga', 'origem_vaga',
       'superior_imediato', 'nome', 'telefone', 'data_inicial', 'data_final',
       'nome_substituto', 'pais', 'estado', 'cidade', 'bairro', 'regiao',
       'local_trabalho', 'vaga_especifica_para_pcd', 'faixa_etaria',
       'horario_trabalho', 'nivel profissional', 'nivel_academico',
       'nivel_ingles', 'nivel_espanhol', 'outro_idioma', 'areas_atuacao',
       'principais_atividades', 'competencia_tecnicas_e_comportamentais',
       'demais_observacoes', 'viagens_requeridas', 'equipamentos_necessarios',
       'habilidades_comportamentais_necessarias', 'valor_venda',
       'valor_compra_1', 'valor_compra_2'],
      dtype='object')

In [29]:
df_vagas.titulo_vaga

0                                         Operation Lead -
1                                   Consultor PP/QM Sênior
2                                    ANALISTA PL/JR C/ SQL
3                           Technical Architect - 11894809
4        Consultor SAP AUTHORIZATION (BCA) -Pleno / Sênior
                               ...
14076                               PMP 5203658 - Dynamics
14077                                 MM com IM - FSR 3910
14078                964 - Assistente fiscal ou financeiro
14079        966 - Analista pleno ou sênior de área fiscal
14080        965 - Assistente ou analista de área contábil
Name: titulo_vaga, Length: 14081, dtype: object

In [30]:
df_vagas.nivel_espanhol.value_counts()

nivel_espanhol
Nenhum           6152
Básico           5821
                 1304
Avançado          332
Intermediário     234
Fluente           227
Técnico            11
Name: count, dtype: int64

In [31]:
df_vagas_filtered = df_vagas[['titulo_vaga','cidade','nivel profissional','nivel_ingles','nivel_espanhol','areas_atuacao','principais_atividades','competencia_tecnicas_e_comportamentais','demais_observacoes','habilidades_comportamentais_necessarias']]
df_vagas_filtered

,titulo_vaga,cidade,nivel profissional,nivel_ingles,nivel_espanhol,areas_atuacao,principais_atividades,competencia_tecnicas_e_comportamentais,demais_observacoes,habilidades_comportamentais_necessarias
0,Operation Lead -,São Paulo,Sênior,Avançado,Fluente,TI - Sistemas e Ferramentas-,Operations Lead\n\nRoles & Responsibilities:\n...,Required Skills:\n• Prior experience in Cloud ...,100% Remoto Período – entre 5 – 6 meses,NaN
1,Consultor PP/QM Sênior,São Paulo,Sênior,Fluente,Nenhum,TI - Desenvolvimento/Programação-,Consultor PP/QM Sr.\n\n• Consultor PP/QM Sênio...,• Consultor PP/QM Sênior com experiencia em pr...,• Início: Imediato • Fim: Jan/22,NaN
2,ANALISTA PL/JR C/ SQL,São Paulo,Analista,Nenhum,Intermediário,TI - Sistemas e Ferramentas-,Descrição – Atividades:\n\no Monitoramento das...,Requisitos mandatórios:\n\no Conhecimentos Téc...,Localização: Remoto Perfil: Analista Pleno ou ...,NaN
3,Technical Architect - 11894809,São Paulo,Analista,Básico,Básico,TI - Projetos-,Descrição/Comentário: Architecture Frameworks ...,Descrição/Comentário: Architecture Frameworks ...,Budgeted Rate - indicate currency and type (ho...,NaN
4,Consultor SAP AUTHORIZATION (BCA) -Pleno / Sênior,São Paulo,Sênior,Intermediário,Nenhum,TI - SAP-,Experiência como Consultor SAP AUTHORIZATION (...,Experiência como Consultor SAP AUTHORIZATION (...,contratação CLT full pela Decision locação rem...,NaN
...,...,...,...,...,...,...,...,...,...,...
14076,PMP 5203658 - Dynamics,São Paulo,Analista,Nenhum,,TI - Desenvolvimento/Programação-,Dynamics,Dynamics,,NaN
14077,MM com IM - FSR 3910,São Paulo,Analista,Avançado,Básico,TI - Projetos-,1 Deve ter boa experiência em configuração de ...,inglês avançado: (tem que se comunicar com o G...,FSR: 3910,NaN
14078,964 - Assistente fiscal ou financeiro,São Paulo,Analista,Básico,Básico,TI - Projetos-,Qualificações técnicas: conhecimento básico em...,"Local: Alphaville, Barueri\nQual região: SP\nI...","Modelo de trabalho: Hibrido, 3 vezes por seman...",NaN
14079,966 - Analista pleno ou sênior de área fiscal,Barueri,Sênior,Básico,Básico,TI - Projetos-,Qualificações técnicas: apuração de impostos r...,"Local: Alphaville, Barueri, SP.\nQual região: ...","Modelo de trabalho: Hibrido, 3 vezes por seman...",NaN
14080,965 - Assistente ou analista de área contábil,Barueri,Analista,Básico,Básico,TI - Projetos-,Qualificações técnicas: reconciliação de conta...,"Local: Alphaville, Barueri, SP.\nRegião: Grand...","Modelo de trabalho: Hibrido, 3 vezes por seman...",NaN

In [32]:
df_applicants.columns

Index(['telefone_recado', 'telefone', 'objetivo_profissional', 'data_criacao',
       'inserido_por', 'email', 'local', 'sabendo_de_nos_por',
       'data_atualizacao', 'codigo_profissional', 'data_aceite', 'nome', 'cpf',
       'fonte_indicacao', 'email.1', 'email_secundario', 'data_nascimento',
       'telefone_celular', 'telefone_recado.1', 'sexo', 'estado_civil', 'pcd',
       'endereco', 'skype', 'url_linkedin', 'facebook', 'download_cv',
       'titulo_profissional', 'area_atuacao', 'conhecimentos_tecnicos',
       'certificacoes', 'outras_certificacoes', 'remuneracao',
       'nivel_profissional', 'qualificacoes', 'experiencias',
       'nivel_academico', 'nivel_ingles', 'nivel_espanhol', 'outro_idioma',
       'instituicao_ensino_superior', 'cursos', 'ano_conclusao', 'outro_curso',
       'id_ibrati', 'email_corporativo', 'cargo_atual', 'projeto_atual',
       'cliente', 'unidade', 'data_admissao', 'data_ultima_promocao',
       'nome_superior_imediato', 'email_superior_imediato'],
      dtype='object')

In [33]:
df_applicants_filtered = df_applicants[['nome','endereco','titulo_profissional','area_atuacao','conhecimentos_tecnicos','certificacoes','outras_certificacoes','nivel_profissional','nivel_ingles','nivel_espanhol']]
df_applicants_filtered

,nome,endereco,titulo_profissional,area_atuacao,conhecimentos_tecnicos,certificacoes,outras_certificacoes,nivel_profissional,nivel_ingles,nivel_espanhol
0,Carolina Aparecida,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Eduardo Rios,são paulo,Analista Administrativo,Administrativa,NaN,NaN,NaN,NaN,Nenhum,Nenhum
2,Pedro Henrique Carvalho,são paulo,Administrativo | Financeiro,Administrativa,NaN,"MS [77-418] MOS: Microsoft Office Word 2013, M...",NaN,NaN,Intermediário,Básico
3,Thiago Barbosa,são paulo,Área administrativa,Administrativa,NaN,NaN,NaN,NaN,Nenhum,Nenhum
4,Diogo das Neves,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
42477,Gabrielly Novaes,NaN,Crm / Líder de Projetos,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42478,Sr. Gabriel Rios,NaN,Crm,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42479,Dr. Mathias da Cunha,NaN,Crm,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42480,Bruna Vieira,NaN,Crm,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42481,Heitor Mendonça,NaN,Crm,NaN,NaN,NaN,NaN,NaN,NaN,NaN

##### Usar df_applicants_filtered e df_vagas_filtered para fazer o match entre candidatos e vagas

In [34]:
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

# Download necessary NLTK data
nltk.download('stopwords')
nltk.download('wordnet')

# Initialize stop words for Portuguese and lemmatizer
stop_words = set(stopwords.words('portuguese'))
lemmatizer = WordNetLemmatizer()
nltk.download('wordnet')

# Function to clean text: remove non-alphanumeric characters, lowercase, lemmatize, and remove stop words
def clean_text(text):
    if isinstance(text, str):
        # Remove non-alphanumeric characters
        text = re.sub(r'[^\w\s]', '', text, re.UNICODE)
        # Lowercase the text
        text = text.lower()
        # Split the text into words, lemmatize each word, and join them back into a string
        text = [lemmatizer.lemmatize(token) for token in text.split(" ")]
        text = [lemmatizer.lemmatize(token, "v") for token in text]
        # Remove stop words
        text = [word for word in text if not word in stop_words]
        # Join the cleaned words
        text = " ".join(text)
        return text
    else:
        return ''

# Apply the cleaning function to all object columns in df_applicants_filtered
for col in df_applicants_filtered.columns:
    if df_applicants_filtered[col].dtype == 'object':
        df_applicants_filtered[col] = df_applicants_filtered[col].astype(str).apply(clean_text)

# Apply the cleaning function to all object columns in df_vagas_filtered
for col in df_vagas_filtered.columns:
    if df_vagas_filtered[col].dtype == 'object':
        df_vagas_filtered[col] = df_vagas_filtered[col].astype(str).apply(clean_text)

# Print the head of the cleaned dataframes
print("Cleaned df_applicants_filtered:")
print(df_applicants_filtered.head())
print("\nCleaned df_vagas_filtered:")
print(df_vagas_filtered.head())

[nltk_data] Downloading package stopwords to /home/vscode/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /home/vscode/nltk_data...
[nltk_data] Downloading package wordnet to /home/vscode/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
/tmp/ipykernel_4715/3900438993.py:36: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_applicants_filtered[col] = df_applicants_filtered[col].astype(str).apply(clean_text)
/tmp/ipykernel_4715/3900438993.py:36: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_applicants_filtered[col] = df_applicants_filtered[col].astype(str).apply(clean_text)
/tmp/ipykernel_4715/3900438993.py:36: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_applicants_filtered[col] = df_applicants_filtered[col].astype(str).apply(clean_text)
/tmp/ipykernel_4715/3900438993.py:36: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_applicants_filtered[col] = df_applicants_filtered[col].astype(str).apply(clean_text)
/tmp/ipykernel_4715/3900438993.py:36: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_applicants_filtered[col] = df_applicants_filtered[col].astype(str).apply(clean_text)
/tmp/ipykernel_4715/3900438993.py:36: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_applicants_filtered[col] = df_applicants_filtered[col].astype(str).apply(clean_text)
/tmp/ipykernel_4715/3900438993.py:36: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_applicants_filtered[col] = df_applicants_filtered[col].astype(str).apply(clean_text)
/tmp/ipykernel_4715/3900438993.py:36: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_applicants_filtered[col] = df_applicants_filtered[col].astype(str).apply(clean_text)
/tmp/ipykernel_4715/3900438993.py:36: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_applicants_filtered[col] = df_applicants_filtered[col].astype(str).apply(clean_text)
/tmp/ipykernel_4715/3900438993.py:36: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_applicants_filtered[col] = df_applicants_filtered[col].astype(str).apply(clean_text)
/tmp/ipykernel_4715/3900438993.py:41: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_vagas_filtered[col] = df_vagas_filtered[col].astype(str).apply(clean_text)
/tmp/ipykernel_4715/3900438993.py:41: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_vagas_filtered[col] = df_vagas_filtered[col].astype(str).apply(clean_text)
/tmp/ipykernel_4715/3900438993.py:41: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_vagas_filtered[col] = df_vagas_filtered[col].astype(str).apply(clean_text)
/tmp/ipykernel_4715/3900438993.py:41: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_vagas_filtered[col] = df_vagas_filtered[col].astype(str).apply(clean_text)
/tmp/ipykernel_4715/3900438993.py:41: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_vagas_filtered[col] = df_vagas_filtered[col].astype(str).apply(clean_text)
/tmp/ipykernel_4715/3900438993.py:41: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_vagas_filtered[col] = df_vagas_filtered[col].astype(str).apply(clean_text)
/tmp/ipykernel_4715/3900438993.py:41: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_vagas_filtered[col] = df_vagas_filtered[col].astype(str).apply(clean_text)
/tmp/ipykernel_4715/3900438993.py:41: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_vagas_filtered[col] = df_vagas_filtered[col].astype(str).apply(clean_text)
/tmp/ipykernel_4715/3900438993.py:41: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_vagas_filtered[col] = df_vagas_filtered[col].astype(str).apply(clean_text)

Cleaned df_applicants_filtered:
                      nome endereco         titulo_profissional  \
0       carolina aparecida      nan                         nan
1              eduardo rio    paulo     analista administrativo
2  pedro henrique carvalho    paulo  administrativo  financeiro
3           thiago barbosa    paulo         área administrativa
4               diogo neve      nan                         nan

     area_atuacao conhecimentos_tecnicos  \
0             nan                    nan
1  administrativa                    nan
2  administrativa                    nan
3  administrativa                    nan
4             nan                    nan

                                       certificacoes outras_certificacoes  \
0                                                nan                  nan
1                                                nan                  nan
2  m 77418 mo microsoft office word 2013 m 77420 ...                  nan
3                                                nan                  nan
4                                                nan                  nan

  nivel_profissional   nivel_ingles nivel_espanhol
0                nan            nan            nan
1                nan         nenhum         nenhum
2                nan  intermediário         básico
3                nan         nenhum         nenhum
4                nan            nan            nan

Cleaned df_vagas_filtered:
                                     titulo_vaga cidade nivel profissional  \
0                                operation lead   paulo             sênior
1                          consultor ppqm sênior  paulo             sênior
2                            analista pljr c sql  paulo           analista
3                  technical architect  11894809  paulo           analista
4  consultor sap authorization bca pleno  sênior  paulo             sênior

    nivel_ingles nivel_espanhol                   areas_atuacao  \
0       avançado        fluente        ti  sistemas ferramentas
1        fluente         nenhum  ti  desenvolvimentoprogramação
2         nenhum  intermediário        ti  sistemas ferramentas
3         básico         básico                    ti  projetos
4  intermediário         nenhum                         ti  sap

                               principais_atividades  \
0  operation lead\n\nroles  responsibilities\n th...
1  consultor ppqm sr\n\n consultor ppqm sênior ex...
2  descrição  atividades\n\no monitoramento inter...
3  descriçãocomentário architecture framework  re...
4  experiência consultor sap authorization bca\np...

              competencia_tecnicas_e_comportamentais  \
0  require skills\n prior experience in cloud inf...
1   consultor ppqm sênior experiencia projetos ro...
2  requisitos mandatórios\n\no conhecimentos técn...
3  descriçãocomentário architecture framework  re...
4  experiência consultor sap authorization bca\np...

                                  demais_observacoes  \
0                     100 remoto período  5  6 meses
1                         início imediato  fim jan22
2  localização remoto perfil analista pleno jr pe...
3  budget rate  indicate currency and type hourly...
4  contratação clt full decision locação remota s...

  habilidades_comportamentais_necessarias
0                                     nan
1                                     nan
2                                     nan
3                                     nan
4                                     nan

/tmp/ipykernel_4715/3900438993.py:41: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_vagas_filtered[col] = df_vagas_filtered[col].astype(str).apply(clean_text)

In [35]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Initialize TF-IDF vectorizer
tfidf_vectorizer = TfidfVectorizer()

# Dictionary to store TF-IDF matrices for applicants
tfidf_applicants = {}

# Iterate through each column of df_applicants_filtered
for col in df_applicants_filtered.columns:
    # Fit and transform the text data
    tfidf_applicants[col] = tfidf_vectorizer.fit_transform(df_applicants_filtered[col])

# Dictionary to store TF-IDF matrices for vagas
tfidf_vagas = {}

# Iterate through each column of df_vagas_filtered
for col in df_vagas_filtered.columns:
    # Fit and transform the text data
    tfidf_vagas[col] = tfidf_vectorizer.fit_transform(df_vagas_filtered[col])

print("TF-IDF matrices for applicants:")
print(tfidf_applicants.keys())
print("\nTF-IDF matrices for vagas:")
print(tfidf_vagas.keys())

TF-IDF matrices for applicants:
dict_keys(['nome', 'endereco', 'titulo_profissional', 'area_atuacao', 'conhecimentos_tecnicos', 'certificacoes', 'outras_certificacoes', 'nivel_profissional', 'nivel_ingles', 'nivel_espanhol'])

TF-IDF matrices for vagas:
dict_keys(['titulo_vaga', 'cidade', 'nivel profissional', 'nivel_ingles', 'nivel_espanhol', 'areas_atuacao', 'principais_atividades', 'competencia_tecnicas_e_comportamentais', 'demais_observacoes', 'habilidades_comportamentais_necessarias'])

In [36]:
df_applicants_filtered

,nome,endereco,titulo_profissional,area_atuacao,conhecimentos_tecnicos,certificacoes,outras_certificacoes,nivel_profissional,nivel_ingles,nivel_espanhol
0,carolina aparecida,nan,nan,nan,nan,nan,nan,nan,nan,nan
1,eduardo rio,paulo,analista administrativo,administrativa,nan,nan,nan,nan,nenhum,nenhum
2,pedro henrique carvalho,paulo,administrativo financeiro,administrativa,nan,m 77418 mo microsoft office word 2013 m 77420 ...,nan,nan,intermediário,básico
3,thiago barbosa,paulo,área administrativa,administrativa,nan,nan,nan,nan,nenhum,nenhum
4,diogo neve,nan,nan,nan,nan,nan,nan,nan,nan,nan
...,...,...,...,...,...,...,...,...,...,...
42477,gabrielly novaes,nan,crm líder projetos,nan,nan,nan,nan,nan,nan,nan
42478,sr gabriel rio,nan,crm,nan,nan,nan,nan,nan,nan,nan
42479,dr mathias cunha,nan,crm,nan,nan,nan,nan,nan,nan,nan
42480,bruna vieira,nan,crm,nan,nan,nan,nan,nan,nan,nan
42481,heitor mendonça,nan,crm,nan,nan,nan,nan,nan,nan,nan

In [37]:
df_vagas_filtered

,titulo_vaga,cidade,nivel profissional,nivel_ingles,nivel_espanhol,areas_atuacao,principais_atividades,competencia_tecnicas_e_comportamentais,demais_observacoes,habilidades_comportamentais_necessarias
0,operation lead,paulo,sênior,avançado,fluente,ti sistemas ferramentas,operation lead\n\nroles responsibilities\n th...,require skills\n prior experience in cloud inf...,100 remoto período 5 6 meses,nan
1,consultor ppqm sênior,paulo,sênior,fluente,nenhum,ti desenvolvimentoprogramação,consultor ppqm sr\n\n consultor ppqm sênior ex...,consultor ppqm sênior experiencia projetos ro...,início imediato fim jan22,nan
2,analista pljr c sql,paulo,analista,nenhum,intermediário,ti sistemas ferramentas,descrição atividades\n\no monitoramento inter...,requisitos mandatórios\n\no conhecimentos técn...,localização remoto perfil analista pleno jr pe...,nan
3,technical architect 11894809,paulo,analista,básico,básico,ti projetos,descriçãocomentário architecture framework re...,descriçãocomentário architecture framework re...,budget rate indicate currency and type hourly...,nan
4,consultor sap authorization bca pleno sênior,paulo,sênior,intermediário,nenhum,ti sap,experiência consultor sap authorization bca\np...,experiência consultor sap authorization bca\np...,contratação clt full decision locação remota s...,nan
...,...,...,...,...,...,...,...,...,...,...
14076,pmp 5203658 dynamic,paulo,analista,nenhum,,ti desenvolvimentoprogramação,dynamic,dynamic,,nan
14077,mm im fsr 3910,paulo,analista,avançado,básico,ti projetos,1 deve ter boa experiência configuração mmim\n...,inglês avançado comunicar global interação in...,fsr 3910,nan
14078,964 assistente fiscal financeiro,paulo,analista,básico,básico,ti projetos,qualificações técnicas conhecimento básico ent...,local alphaville barueri\nqual região sp\nidio...,modelo trabalho hibrido 3 vezes semana escritó...,nan
14079,966 analista pleno sênior área fiscal,barueri,sênior,básico,básico,ti projetos,qualificações técnicas apuração impostos retid...,local alphaville barueri sp\nqual região grand...,modelo trabalho hibrido 3 vezes semana escritó...,nan
14080,965 assistente analista área contábil,barueri,analista,básico,básico,ti projetos,qualificações técnicas reconciliação contas ba...,local alphaville barueri sp\nregião grande pau...,modelo trabalho hibrido 3 vezes semana escritó...,nan

In [ ]:
df_vagas_filtered
df_applicants_filtered

In [41]:
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import TfidfVectorizer
import numpy as np

# Função para calcular a similaridade entre uma vaga e todos os candidatos
def rank_applicants_for_job(vaga_idx, df_applicants_filtered):
    # Colunas para comparar (ajuste conforme necessário)
    columns_to_compare = [
        ('titulo_vaga', 'titulo_profissional'),
        ('cidade', 'endereco'),
        ('nivel profissional', 'nivel_profissional'),
        ('nivel_ingles', 'nivel_ingles'),
        ('nivel_espanhol', 'nivel_espanhol'),
        ('areas_atuacao', 'area_atuacao'),
        ('principais_atividades', 'conhecimentos_tecnicos'),
        ('competencia_tecnicas_e_comportamentais', 'certificacoes'),
        # 'demais_observacoes' e 'habilidades_comportamentais_necessarias' podem ser incluídas se fizer sentido
    ]
    
    total_score = np.zeros(len(df_applicants_filtered))
    for vaga_col, applicant_col in columns_to_compare:
        if vaga_col in df_vagas_filtered.columns and applicant_col in df_applicants_filtered.columns:
            # Combine texts for fitting vectorizer
            vaga_text = df_vagas_filtered.loc[vaga_idx, vaga_col]
            applicants_text = df_applicants_filtered[applicant_col].fillna("").astype(str).tolist()
            combined_texts = [vaga_text] + applicants_text
            vectorizer = TfidfVectorizer()
            tfidf_matrix = vectorizer.fit_transform(combined_texts)
            vaga_vec = tfidf_matrix[0]
            applicants_mat = tfidf_matrix[1:]
            # Calcula similaridade entre a vaga e todos os candidatos para esta coluna
            sim = cosine_similarity(vaga_vec, applicants_mat).flatten()
            total_score += sim
    
    # Retorna os índices dos top 10 candidatos
    top10_idx = np.argsort(-total_score)[:10]
    return df_applicants_filtered.iloc[top10_idx].assign(score=total_score[top10_idx])

# Função para mostrar os top 10 candidatos para uma vaga selecionada pelo índice
def mostrar_top10_para_vaga(vaga_idx, df_vagas_filtered, df_applicants_filtered):
    top10 = rank_applicants_for_job(vaga_idx, df_applicants_filtered)
    print(f"Top 10 candidatos para a vaga: {df_vagas_filtered.loc[vaga_idx, 'titulo_vaga']}")
    display(top10[['nome', 'titulo_profissional', 'area_atuacao', 'score']])

# Demonstração com a primeira vaga (índice 0)
mostrar_top10_para_vaga(0, df_vagas_filtered, df_applicants_filtered)

Top 10 candidatos para a vaga: operation lead

,nome,titulo_profissional,area_atuacao,score
18957,laís caldeira,analista negócios implantação suporte ecomm...,ti processos negócios ti projetos ti sistem...,3.668310
16674,murilo santos,lous note domino ingles,ti infraestrutura ti projetos ti segurança ...,3.610831
29386,juan castro,nan,gestão alocação recursos ti ti desenvolviment...,3.544080
20909,raquel cassiano,presales system engineer arquiteto soluções,ti arquitetura ti desenvolvimentodesign ti ...,3.532511
21171,arthur abreu,nan,ti desenvolvimentodesign ti desenvolvimentom...,3.528022
40739,alana macedo,consultor java soa oracle,ti arquitetura ti desenvolvimentodesign ti ...,3.292911
37529,dr benicio peixoto,lider integracao sap,ti processos negócios ti projetos ti qualid...,3.284045
23014,julia farias,analista negócios sênior,administrativa financeiracontroladoria gestão ...,3.278091
3312,nathan souza,gestão projetos,ti processos negócios ti projetos ti suporte,3.263399
19217,guilherme porto,gerente projetos pmo,administrativa ti governança ti processos ne...,3.247484